### PR TITLE
Add Google Colab Demo

### PR DESCRIPTION
**Pull request by xhlulu**
The demo on HG Spaces is amazing! I used it for a few photos and really like it.

Unfortunately it seems it's getting quite crowded and takes over 20min to process due to the queue. Also it runs on a CPU. 

I added a colab notebook that lets you upload a photo and run the model. It works on both CPU and GPUs. You can see what it looks like here: https://colab.research.google.com/github/xhlulu/animegan2-pytorch/blob/main/colab_demo.ipynb

### CODE REVIEW

**Comment by AK391** [comment]
cool, also the demo on HF is using gpu now, try it out :)

**Comment by bryandlee** [comment]
Thanks! Actually there is a colab demo in readme so I updated it with the hub model.

**Comment by xhlulu** [comment]
@bryandlee the notebook is different. it is specifically a interact jupyter app that lets you upload your file, select the file type and run the model without having to run any code cell.

**Comment by bryandlee** [comment]
I see! That gives better accessibility

**Pull request merged**
